apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: myaksst4603.file.core.windows.net
    path: /myaksst4603/export
