apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsdata
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: aksmyst.file.core.windows.net
    path: /aksmyst/export
